name: composite custom action workflow

on:
    workflow_call:

jobs:
    composite-custom-action:
        runs-on: ubuntu-latest
        steps:
            - name: get-label
              id: label
              uses: 77jennifer77/github-actions-by-example-reusable-workflows/.github/actions/get-labels-composite@get-labels-composite-v0
              with:
                  label-key: bump
                  github-token: ${{ secrets.GITHUB_TOKEN }}
